# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sf_video.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sfVideo(object):
    def setupUi(self, sfVideo):
        sfVideo.setObjectName("sfVideo")
        sfVideo.resize(910, 900)
        self.progressBar = QtWidgets.QProgressBar(sfVideo)
        self.progressBar.setGeometry(QtCore.QRect(630, 110, 241, 30))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(sfVideo)
        self.progressBar_2.setGeometry(QtCore.QRect(630, 160, 241, 30))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(sfVideo)
        self.progressBar_3.setGeometry(QtCore.QRect(630, 210, 241, 30))
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtWidgets.QProgressBar(sfVideo)
        self.progressBar_4.setGeometry(QtCore.QRect(630, 260, 241, 30))
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setObjectName("progressBar_4")
        self.progressBar_5 = QtWidgets.QProgressBar(sfVideo)
        self.progressBar_5.setGeometry(QtCore.QRect(630, 310, 241, 30))
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setObjectName("progressBar_5")
        self.progressBar_6 = QtWidgets.QProgressBar(sfVideo)
        self.progressBar_6.setGeometry(QtCore.QRect(630, 360, 241, 30))
        self.progressBar_6.setProperty("value", 0)
        self.progressBar_6.setObjectName("progressBar_6")
        self.progressBar_7 = QtWidgets.QProgressBar(sfVideo)
        self.progressBar_7.setGeometry(QtCore.QRect(630, 410, 241, 30))
        self.progressBar_7.setProperty("value", 0)
        self.progressBar_7.setObjectName("progressBar_7")
        self.label = QtWidgets.QLabel(sfVideo)
        self.label.setGeometry(QtCore.QRect(30, 410, 131, 40))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(sfVideo)
        self.label_2.setGeometry(QtCore.QRect(200, 410, 250, 40))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(sfVideo)
        self.label_3.setGeometry(QtCore.QRect(500, 100, 130, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(sfVideo)
        self.label_4.setGeometry(QtCore.QRect(500, 150, 130, 40))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(sfVideo)
        self.label_5.setGeometry(QtCore.QRect(500, 200, 130, 40))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(sfVideo)
        self.label_6.setGeometry(QtCore.QRect(500, 250, 130, 40))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(sfVideo)
        self.label_7.setGeometry(QtCore.QRect(500, 300, 130, 40))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(sfVideo)
        self.label_8.setGeometry(QtCore.QRect(500, 350, 130, 40))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(sfVideo)
        self.label_9.setGeometry(QtCore.QRect(500, 400, 130, 40))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(sfVideo)
        self.label_10.setGeometry(QtCore.QRect(50, 50, 420, 315))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(sfVideo)
        self.pushButton.setGeometry(QtCore.QRect(620, 30, 191, 41))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(sfVideo)
        QtCore.QMetaObject.connectSlotsByName(sfVideo)

    def retranslateUi(self, sfVideo):
        _translate = QtCore.QCoreApplication.translate
        sfVideo.setWindowTitle(_translate("sfVideo", "SoulFlow-选择视频"))
        self.label.setText(_translate("sfVideo", "帧:"))
        self.label_2.setText(_translate("sfVideo", "推理速度:"))
        self.label_3.setText(_translate("sfVideo", "快乐"))
        self.label_4.setText(_translate("sfVideo", "惊讶"))
        self.label_5.setText(_translate("sfVideo", "其他"))
        self.label_6.setText(_translate("sfVideo", "厌恶"))
        self.label_7.setText(_translate("sfVideo", "恐惧"))
        self.label_8.setText(_translate("sfVideo", "压抑"))
        self.label_9.setText(_translate("sfVideo", "悲伤"))
        self.label_10.setText(_translate("sfVideo", "(视频缩略图)"))
        self.pushButton.setText(_translate("sfVideo", "选择视频文件"))

